### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by rowanhemsi** [best-practice-and-impact/gptables#230] opened 2024-06-27 08:57 UTC
Examples have been added haphazardly in the past and should be updated to clearly demonstrate key functionality. 

Definition of done - decide whether to add to or replace previous examples and merge

**Comment by ellie-o** [comment] 2024-06-27 09:54
Duplicate of #128 - when 128 is complete this can move to done too

**Closed** 2024-06-27 09:57 UTC
Labels: duplicate :eyes:, enhancement :sparkles:
